In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5]) # انشاء مصفوفات  D1

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
a.size

5

In [8]:
a.itemsize #حجم بالبايت لكل عنصر في المصفوفة 

4

In [9]:
a.data # مكان تخزين المصفوفة على الذاكرة

In [10]:
# انشاء مصفوفات D3 &D2
b = np.array([[1,2,3],[3,4,5]])

In [12]:
print(b.dtype)
print(b.ndim)
print(b.shape)
print(b.size)

int32
2
(2, 3)
6


In [13]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
print(c.dtype)
print(c.ndim)
print(c.shape)
print(c.size)

int32
3
(2, 2, 2)
8


In [15]:
x = np.array([2.6, 4.9])
x.dtype

dtype('float64')

In [16]:
x = np.array([2.6, 4.9], dtype=complex) # لو أضفنا نوع الكومبلكس الاعداد المركبة راح يتغير النوع لها نسميها أعداد تخيلية 
x.dtype

dtype('complex128')

In [17]:
s = np.array(['N','M','V'])
s.dtype

dtype('<U1')

In [18]:
e = np.array([False,True, False])
e.dtype

dtype('bool')

In [20]:
m = np.array(['N', 3, True])
#m.dtype
m  # حولها عندي كلها لنفس النوع متجانس 

array(['N', '3', 'True'], dtype='<U11')

In [22]:
# و نقدر نغير النوع باستخدام 
r = np.array(['1', '4'])
r.astype(int)

array([1, 4])

In [3]:
# في طريقة اخرى لانشاء المصفوفات عن طريق التيوبل 
d = np.array((1,2))
d

array([1, 2])

In [5]:
# وايضا نستطيع انشاء مصفوفة عن طريق لست و تيوبل بنفس الوقت 
h = np.array([(1,3),[3,8]])
h

array([[1, 3],
       [3, 8]])

In [6]:
np.zeros([6,9])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.arange(3,6) # مصفوفة تبدأ عند ثلاثة و تنتهي عند الستة 

array([3, 4, 5])

In [9]:
np.arange(1,100,10) # هذي عدد الأرقام بينهم 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [10]:
np.arange(1,80,3.8)

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. , 23.8, 27.6, 31.4, 35.2, 39. ,
       42.8, 46.6, 50.4, 54.2, 58. , 61.8, 65.6, 69.4, 73.2, 77. ])

In [13]:
np.linspace(1,10,3) # هنا عدد الأرقام في المصفوفة 

array([ 1. ,  5.5, 10. ])

In [ ]:
# و الفرق بينهم أن range لا تحتوي على نقطة النهاية وlinspace تحتوي على نقطة النهاية 

In [16]:
# إنشاء مصفوفات بال random
np.random.random((2,2))

array([[0.76494943, 0.02498133],
       [0.12653359, 0.17240107]])

In [18]:
np.random.rand(4,4) # أرقام عشوائية محدودة من 0 إلى 1

array([[0.90209998, 0.0049326 , 0.41545538, 0.01978337],
       [0.40681534, 0.55848794, 0.1093203 , 0.86143306],
       [0.04104636, 0.38663564, 0.06525639, 0.59799227],
       [0.36683271, 0.36584226, 0.60603248, 0.1167464 ]])

In [19]:
np.random.randn(2,3) # عينة من التوزيع الطبيعي 

array([[-0.32281195, -0.74408091,  1.07877536],
       [-2.01862174,  0.25290566,  1.79326773]])

In [22]:
np.random.randint(5,12)

11

In [24]:
np.random.randint(12, size=5)

array([11,  2,  8,  2,  3])

In [25]:
np.random.randint(12, size=(2,2))

array([[0, 9],
       [3, 8]])

In [26]:
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [33]:
np.full((2,2), [8,4])

array([[8, 4],
       [8, 4]])

In [34]:
np.full((4,4), [8,4,7,2])

array([[8, 4, 7, 2],
       [8, 4, 7, 2],
       [8, 4, 7, 2],
       [8, 4, 7, 2]])

In [35]:
np.eye(5) # تنشأ مصفوفة الوحدة  , وهي مصفوفة مكونة من أصفار ماعدا قطرها 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.empty([2,2], dtype=int)

array([[8, 4],
       [7, 2]])

In [2]:
z = np.array([[0,1],[6,7],[8,9]])

In [3]:
np.ravel(z)

array([0, 1, 6, 7, 8, 9])

In [5]:
# Indexing في المصفوفات أحادية الأبعاد و في ثنائية الأبعاد 
w = np.arange(10 , 16)
w

array([10, 11, 12, 13, 14, 15])

In [6]:
w[4]

14

In [7]:
w[-1]

15

In [8]:
w[-6]

10

In [10]:
w[[1,2,4]]

array([11, 12, 14])

In [11]:
w = np.arange(10,19).reshape((3,3))
w # الآن شكل مصفوفة ثنائية الأبعاد

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
w[1,2]

15

In [13]:
w[0,2]

12

In [14]:
w[2][2]

18

In [15]:
w[1] # صف كامل 

array([13, 14, 15])

In [16]:
# مفهوم Slicing
q = np.arange(10,16)
q

array([10, 11, 12, 13, 14, 15])

In [17]:
q[1:4]

array([11, 12, 13])

In [18]:
q[0:5:2]

array([10, 12, 14])

In [19]:
q[:5:3]

array([10, 13])

In [20]:
q[::2]

array([10, 12, 14])

In [21]:
q[:5:]

array([10, 11, 12, 13, 14])

In [22]:
q[:] # بترجع لنا كامل المصفوفة 

array([10, 11, 12, 13, 14, 15])

In [24]:
A = np.arange(10,19).reshape((3,3)) # ثنائية الأبعاد
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
A[0,:] # عند إضافة , بيرجع لي الصف 

array([10, 11, 12])

In [26]:
A[0:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
A[0:3, 0:3]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
A[[[0:2] : [0:2]]

SyntaxError: invalid syntax (1851106390.py, line 1)

In [53]:
A[0:3,[0,2]]

array([[10, 12],
       [13, 15],
       [16, 18]])

In [56]:
A[1,:] # هذي تطلع الصفوف 

array([13, 14, 15])

In [57]:
A[2,:]

array([16, 17, 18])

In [58]:
A[:,1] # الأعمدة 

array([11, 14, 17])

In [59]:
A[:,2]

array([12, 15, 18])

In [60]:
A[[0,2],0:2] # نرجع عناصر غير متجاورة 

array([[10, 11],
       [16, 17]])

In [61]:
A[[0,1],0:2]

array([[10, 11],
       [13, 14]])

In [62]:
A[[0,0],0:2]

array([[10, 11],
       [10, 11]])