In [1]:
import numpy as np


In [3]:
# تغيير شكل المصفوفات التلاعب بها 
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a.reshape(3,4) # هذا أول تغيير لشكل المصفوفة بحيث اجيب رقمين حاصل ضربهم 12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# تغير شكل المصفوفة إلى مصفوفة من صف واحد 
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# هذي تحول الصفوف لأعمدة و الأعمدة لصفوف
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
# العمليات الرياضية 
n = np.arange(4)
n

array([0, 1, 2, 3])

In [12]:
n + 4

array([4, 5, 6, 7])

In [13]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [14]:
n + b

array([ 4,  6,  8, 10])

In [15]:
np.add(n,b)

array([ 4,  6,  8, 10])

In [16]:
n-b

array([-4, -4, -4, -4])

In [17]:
np.subtract(n,b)

array([-4, -4, -4, -4])

In [18]:
n*b

array([ 0,  5, 12, 21])

In [19]:
np.multiply(n,b)

array([ 0,  5, 12, 21])

In [20]:
n / b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [21]:
np.divide(n,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [23]:
#  أحد مفاهيم الجبر الخطي مفهوم ضرب المصفوفات 
g = np.array([[4,5,6], [8,9,7]])
g.shape

(2, 3)

In [25]:
m = np.array([1,2,3])
m.shape

(3,)

In [26]:
# ننشأ مصفوفة جديدة نحفظ فيها النتيجة 
c = np.dot(g,m)
c

array([32, 47])

In [2]:
#increment كتابة علامة الجمع قبل المساواة 
n = np.arange(4)
n

array([0, 1, 2, 3])

In [3]:
n +=1
n

array([1, 2, 3, 4])

In [5]:
# decrement
n -= 2
n

array([-2, -1,  0,  1])

In [6]:
n *= 2
n

array([-4, -2,  0,  2])

In [7]:
e = np.arange(1,5)
e

array([1, 2, 3, 4])

In [8]:
#Universal Functions
# مثلا الجذر التربيعي
np.sqrt(e)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [9]:
#  تساعدنا نعرف اللوغارتم أو معكوس الدالة الأسية
np.log(e)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [10]:
# تساعدنا نعرف قيم الدالة المثلثية و دالة الجيب 
np.sin(e)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [11]:
# تساعدنا نعرف الدالة الأسية ألي اساسهاE
np.exp(e)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [12]:
# Aggregate Functions 
d = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
d

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [13]:
d.sum()

15.0

In [14]:
d.min()

0.3

In [15]:
d.max()

5.7

In [16]:
d.argmax()

3

In [17]:
d.mean()

3.0

In [18]:
d.std()

2.0079840636817816

In [9]:
# مفهوم itreting
x = np.arange(0,20).reshape((2,10))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [10]:
for i in x:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [11]:
for row in x:
    for item in row:
        print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [12]:
for item in x.flat:  # تساعدنا نحول 2d array الى d 1 
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [13]:
np.apply_along_axis(np.mean, axis=1, arr=x) #تتيح ننفذ عمليات على المصفوفة بدون كتابة اللوب 

array([ 4.5, 14.5])

In [14]:
np.apply_along_axis(np.mean, axis=0, arr=x)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [15]:
def fun1(x):
    return x +300

In [16]:
np.apply_along_axis(fun1, axis=0, arr=x)

array([[300, 301, 302, 303, 304, 305, 306, 307, 308, 309],
       [310, 311, 312, 313, 314, 315, 316, 317, 318, 319]])

In [17]:
# Conditions
c = np.random.random((4,4))
c

array([[0.56504698, 0.03168699, 0.47881359, 0.54499651],
       [0.15804327, 0.47880153, 0.71238612, 0.14192712],
       [0.50815183, 0.24841513, 0.74782637, 0.37047587],
       [0.05585413, 0.09523533, 0.2128105 , 0.94769338]])

In [18]:
c < 0.2

array([[False,  True, False, False],
       [ True, False, False,  True],
       [False, False, False, False],
       [ True,  True, False, False]])

In [19]:
c[c < 0.2]

array([0.03168699, 0.15804327, 0.14192712, 0.05585413, 0.09523533])

In [20]:
z = np.array([
    [2, 1, 0],
    [5, 6, 7],
    [3, 8, 9]
])


In [23]:
z[:]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [22]:
z[::1]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [24]:
z[0:3,0:3]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [25]:
z[[0,1],[0,2]]

array([2, 7])

In [26]:
z[1][1]

6

In [27]:
q = np.ones((3,3))
q

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
n = np.zeros((3,3))
n

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.vstack((q,n)) # تستخدم لدمج المصفوفتين بشكل عمودي 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.hstack((q,n)) # تستخدم لدمج المصفوفتين بشكل أفقي 

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [32]:
a = np.array([1,2,3])
b = np.array([4,5,3])
c = np.array([8,7,6])

In [33]:
np.column_stack((a,b,c)) # تدمج المصفوفات كأعمدة 

array([[1, 4, 8],
       [2, 5, 7],
       [3, 3, 6]])

In [34]:
np.row_stack((a,b,c)) # تدمج المصفوفات كصفوف

array([[1, 2, 3],
       [4, 5, 3],
       [8, 7, 6]])

In [36]:
v = np.arange(16).reshape((4,4))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
[a,b] =np.hsplit(v,2) # تقسم المصفوفة إلى مصفوفتين بشكل أفقي 

In [38]:
a

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [39]:
b

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [40]:
[a,b] =np.vsplit(v,2) # تقسمها بشكل عمودي

In [41]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
[x,y,z]= np.split(a, [1,3],axis=1) # بتقسمها بشكل غير منظم

In [47]:
x

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [48]:
y

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [49]:
z

array([[ 3],
       [ 7],
       [11],
       [15]])

In [50]:
[x,y,z]= np.split(a, [2,3],axis=0)

In [51]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
y

array([[ 8,  9, 10, 11]])

In [53]:
z

array([[12, 13, 14, 15]])

In [54]:
w = np.array([1,2,3,4])
b=w

In [56]:
print(w)
print(b)

[1 2 3 4]
[1 2 3 4]


In [58]:
w[3]=0 # w و b  viwe  لبعض
print(w)
print(b)

[1 2 3 0]
[1 2 3 0]


In [60]:
c = w[0:2]
c

array([1, 2])

In [61]:
print(w)
print(c)

[1 2 3 0]
[1 2]


In [62]:
w = np.array([1,2,3,4])
b= w.copy()
print(w)
print(b)

[1 2 3 4]
[1 2 3 4]


In [63]:
w[0] = 0 # اذا المصفوفة نسخة من اخرى مارح تتأثر فيها 
print(w)
print(b)

[0 2 3 4]
[1 2 3 4]


In [64]:
x = np.array([[11, 12], [13, 14], [15, 16]])
y = np.arange(1, 4)


In [65]:
np.column_stack((y,x))

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [66]:
np.column_stack((x,y))

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

In [69]:
x = np.array(["A", "B", "C", "D", "E"])
y = x[0:2]
z = x.copy()
print(z)

['A' 'B' 'C' 'D' 'E']


In [71]:
a=np.array([
[ 9, 6, 3],
[ 8, 4, 2],
[ 7, 1, 5]
])


In [73]:
np.ravel(a)

array([9, 6, 3, 8, 4, 2, 7, 1, 5])

In [74]:
np.transpose(a)

array([[9, 8, 7],
       [6, 4, 1],
       [3, 2, 5]])